"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const router = express_1.default.Router();
exports.default = router;
const index_1 = require("../Controllers/index");
const Util_1 = require("../Util");
router.get('/', index_1.DisplayHomePage);
router.get('/home', index_1.DisplayHomePage);
router.get('/about', index_1.DisplayAboutPage);
router.get('/projects', index_1.DisplayProjectPage);
router.get('/services', index_1.DisplayServicesPage);
router.get('/contact', index_1.DisplayContactPage);
router.post('/contact', index_1.ProcessContactPage);
router.get('/condoUnits', Util_1.AuthGuard, index_1.DisplayCondoUnits);
router.get('/condo/create/:id', Util_1.AuthGuard, index_1.DisplayCreateCondoUnits);
router.post('/condo/create/:id', Util_1.AuthGuard, index_1.ProcessCreateCondoUnits);
router.get('/maintenanceRequest', Util_1.AuthGuard, index_1.DisplayMaintenanceRequest);
router.get('/maintenanceRequestList', Util_1.AuthGuard, index_1.DisplayMaintenanceRequestList);
router.post('/maintenanceRequest', Util_1.AuthGuard, index_1.ProcessMaintenanceRequest);
router.get('/login', index_1.DisplayLoginPage);
router.post('/login', index_1.ProcessLoginPage);
router.get('/register', index_1.DisplayRegisterPage);
router.post('/register', index_1.ProcessRegisterPage);
router.get('/logout', index_1.ProcessLogoutPage);
router.get('/profile', Util_1.AuthGuard, index_1.DisplayProfilePage);
router.post('/profile', Util_1.AuthGuard, index_1.ProcessProfilePage);
router.get('/changePassword', Util_1.AuthGuard, index_1.ChangePassWordPage);
router.post('/changePassword', Util_1.AuthGuard, index_1.ProcessChangePassWordPage);
router.get('/parkingpermit', Util_1.AuthGuard, index_1.DisplayParkingPermit);
router.post('/parkingpermit', Util_1.AuthGuard, index_1.ProcessParkingPermit);
router.get('/thanks', index_1.DisplayThankYou);
router.get('/renovationList', Util_1.AuthGuard, index_1.DisplayRenovations);
router.get('/renovations/create', Util_1.AuthGuard, index_1.DisplayCreateRenovations);
router.post('/renovations/create', Util_1.AuthGuard, index_1.ProcessRenovations);
module.exports = router;
//# sourceMappingURL=index.js.map